=== simon-japan/SpaceGame/configuration/map.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="root" type="rootType"/>
  <xs:complexType name="tileTypeType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="sprite" use="optional"/>
        <xs:attribute type="xs:string" name="mapid" use="optional"/>
        <xs:attribute type="xs:string" name="tangible" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="rootType">
    <xs:sequence>
      <xs:element type="tileTypesType" name="tileTypes"/>
      <xs:element type="xs:string" name="map"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="tileTypesType">
    <xs:sequence>
      <xs:element type="tileTypeType" name="tileType" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== simon-japan/SpaceGame/configuration/map.xml
<?xml version="1.0" encoding="UTF-8"?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="map.xsd">
    <tileTypes>
        <tileType sprite="tile_red" mapid="00" tangible="false"/>
        <tileType sprite="tile_green" mapid="01" tangible="false"/>
        <tileType sprite="tile_blue" mapid="02" tangible="false"/>
        <tileType sprite="tile_topleft" mapid="03" tangible="true"/>
        <tileType sprite="tile_left" mapid="04" tangible="true"/>
        <tileType sprite="tile_bottomleft" mapid="05" tangible="true"/>
        <tileType sprite="tile_top" mapid="06" tangible="true"/>
        <tileType sprite="tile_center" mapid="07" tangible="true"/>
        <tileType sprite="tile_bottom" mapid="08" tangible="true"/>
        <tileType sprite="tile_topright" mapid="09" tangible="true"/>
        <tileType sprite="tile_right" mapid="10" tangible="true"/>
        <tileType sprite="tile_bottomright" mapid="11" tangible="true"/>
    </tileTypes>
    <map>
        00 01 02 00 01 02 00 01 02 00 01 02
        01 03 06 06 09 00 01 03 06 06 09 00
        02 00 01 02 10 01 02 00 01 02 10 01
        00 01 02 00 10 02 00 01 02 00 10 02
        01 05 08 08 11 00 01 05 08 08 11 00
        02 00 01 02 00 01 02 00 01 02 00 01
        00 01 02 00 01 02 00 01 02 00 01 02
        01 03 06 06 09 00 01 03 06 06 09 00
        02 00 01 02 10 01 02 00 01 02 10 01
        00 01 02 00 10 02 00 01 02 00 10 02
        01 05 08 08 11 00 01 05 08 08 11 00
        02 00 01 02 00 01 02 00 01 02 00 01
    </map>
</root>

=== simon-japan/SpaceGame/configuration/test_map.xml
<?xml version="1.0" encoding="UTF-8"?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="map.xsd">
    <tileTypes>
        <tileType sprite="tile_ground" mapid="00" tangible="false"/>
        <tileType sprite="tile_ground" mapid="01" tangible="false"/>
        <tileType sprite="tile_trak3" mapid="02" tangible="false"/>
        <tileType sprite="tile_blue_topleft" mapid="03" tangible="true"/>
        <tileType sprite="tile_blue_left" mapid="04" tangible="true"/>
        <tileType sprite="tile_blue_bottomleft" mapid="05" tangible="true"/>
        <tileType sprite="tile_blue_top" mapid="06" tangible="true"/>
        <tileType sprite="tile_blue_center" mapid="07" tangible="true"/>
        <tileType sprite="tile_blue_bottom" mapid="08" tangible="true"/>
        <tileType sprite="tile_blue_topright" mapid="09" tangible="true"/>
        <tileType sprite="tile_blue_right" mapid="10" tangible="true"/>
        <tileType sprite="tile_blue_bottomright" mapid="11" tangible="true"/>
    </tileTypes>
    <Characters>

    </Characters>
    <map>
        00 00 00 00 00 00
        00 03 06 06 09 00
        00 00 00 00 00 00
        00 00 00 00 00 00
        00 00 00 00 00 00
        00 00 00 00 00 00
    </map>
</root>
