=== simon-japan/SpaceGame/configuration/sprites.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="root" type="rootType"/>
  <xs:complexType name="rootType">
    <xs:sequence>
      <xs:element type="texturesType" name="textures"/>
      <xs:element type="spritesType" name="sprites"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="spriteType">
    <xs:sequence>
      <xs:element type="clipType" name="clip" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="name" use="optional"/>
  </xs:complexType>
  <xs:complexType name="spritesType">
    <xs:sequence>
      <xs:element type="spriteType" name="sprite" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="textureType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="name" use="optional"/>
        <xs:attribute type="xs:string" name="file" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="texturesType">
    <xs:sequence>
      <xs:element type="textureType" name="texture" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="clipType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="texture" use="optional"/>
        <xs:attribute type="xs:string" name="x" use="optional"/>
        <xs:attribute type="xs:string" name="y" use="optional"/>
        <xs:attribute type="xs:string" name="w" use="optional"/>
        <xs:attribute type="xs:string" name="h" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
</xs:schema>

=== simon-japan/SpaceGame/configuration/sprites.xml
<?xml version="1.0" encoding="UTF-8"?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="sprites.xsd">
    <textures>
        <texture name="tiles" file="/Users/simon/Desktop/images/tiles.png">
            <clip x="0" y="0" w="80" h="80" id="tile_red" is_sprite="true"/>
            <clip x="0" y="80" w="80" h="80" id="tile_green" is_sprite="true"/>
            <clip x="0" y="160" w="80" h="80" id="tile_blue" is_sprite="true"/>
            <clip x="80" y="0" w="80" h="80" id="tile_topleft" is_sprite="true"/>
            <clip x="80" y="80" w="80" h="80" id="tile_left" is_sprite="true"/>
            <clip x="80" y="160" w="80" h="80" id="tile_bottomleft" is_sprite="true"/>
            <clip x="160" y="0" w="80" h="80" id="tile_top" is_sprite="true"/>
            <clip x="160" y="80" w="80" h="80" id="tile_center" is_sprite="true"/>
            <clip x="160" y="160" w="80" h="80" id="tile_bottom" is_sprite="true"/>
            <clip x="240" y="0" w="80" h="80" id="tile_topright" is_sprite="true"/>
            <clip x="240" y="80" w="80" h="80" id="tile_right" is_sprite="true"/>
            <clip x="240" y="160" w="80" h="80" id="tile_bottomright" is_sprite="true"/>
        </texture>
        <texture name="dot" file="/Users/simon/Desktop/images/dot.bmp">
            <clip id="dot" x="0" y="0" w="20" h="20" is_sprite="true"/>
        </texture>
    </textures>
</root>
